### ISSUE TITLE
Nextcloud Hub 21

### ISSUE THREAD

**Issue by dumblob** [downtownallday/cloudinabox#13]
It seems the new release of NC offers some significant changes (PHP 8.0 required, new backend written in Rust, etc.).

https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/

Has anyone tried it already? Will it have any impact on cloudinabox (any changes needed)?

**Comment by downtownallday** [comment]
I don't think anyone has tried it yet. It can take [weeks](https://nextcloud.com/release-channels/) for it to become available. Also, the docs say php8 is not required, just that the new version of Nextcloud is compatible with it. On paper, I don't see any reason why it wouldn't work just fine on a Ubuntu 20 machine.

**Comment by dumblob** [comment]
Closing as there seems to be not much to do except for changing versions (both NC and PHP) in the scripts and maybe explicitly installing `php-filter` module as per https://github.com/nextcloud/server/issues/25999 (note, there seems to be quite some potential issues when upgrading from NC 20 to NC 21: https://github.com/nextcloud/server/issues/25981 https://github.com/nextcloud/server/issues/25913 https://github.com/nextcloud/server/issues/25897 https://github.com/nextcloud/server/issues/25834 https://github.com/nextcloud/server/issues/25831 https://github.com/nextcloud/server/issues/25830 https://github.com/nextcloud/server/issues/25813 https://github.com/nextcloud/server/issues/25808 https://github.com/nextcloud/server/issues/25807 https://github.com/nextcloud/server/issues/25791 https://github.com/nextcloud/server/issues/25790 https://github.com/nextcloud/server/issues/25761 https://github.com/nextcloud/server/issues/25759 https://github.com/nextcloud/server/issues/25756 https://github.com/nextcloud/server/issues/25749 https://github.com/nextcloud/server/issues/25746 https://github.com/nextcloud/server/issues/25742 https://github.com/nextcloud/server/issues/25736 ).
