### ISSUE TITLE
Cron frequency for NC

### ISSUE THREAD

**Issue by dumblob** [downtownallday/cloudinabox#2]
I've found out that NC guys changed their recommended cron frequency from every 15 to every 5 minutes. Does *cloudinabox* use these 5 minutes or another interval?

**Comment by downtownallday** [comment]
Currently 15, so probably should be changed. Do you have a link that explains what benefit it provides?

**Comment by dumblob** [comment]
There were some long term issues with email and other caches not updating leading to many races and poor user experience. I saw it in https://github.com/nextcloud/mail/issues/3049#issuecomment-630667105 and the docs also say so: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/background_jobs_configuration.html

**Comment by dumblob** [comment]
Seems fixed, thanks!
