### ISSUE TITLE
Possibility to run together with MiaB-LDAP on the very same Ubuntu system instance?

### ISSUE THREAD

**Issue by dumblob** [downtownallday/cloudinabox#4]
I've finally come to try to install cloudinabox, but I'd like to have it together with MiaB-LDAP on one machine.

When reading [readme of MiaB-LDAP](https://github.com/downtownallday/mailinabox-ldap ) I'm not sure whether the services won't "bite" each other as I got scared by:

>During setup you will be prompted for the hostname and web prefix of your remote Nextcloud box.
>
>The setup mod will configure Roundcube and Z-Push (ActiveSync) to use the remote Nextcloud for contacts and calendar instead of the local Nextcloud, which will be disabled (browsing to /cloud will fail). Old contacts will still be available in Roundcube, but read-only. Users can drag them into the remote Nextcloud.

In addition to that I'm afraid there might be some inconsistency with DNS handling (`mailinabox-ldap` might want something else than `cloudinabox` and vice versa), then with backups, system users & groups, etc.

Any thoughts before I'll dive into the scripts to find out myself?

**Comment by downtownallday** [comment]
miab-ldap and cloudinabox must be on different servers

**Comment by dumblob** [comment]
Hm, and would it conflict with the scripts etc. if both servers shared the same domain name? In other words, does MiaB-LDAP modify only MX records and if not, are the changes compatible ("mergeable") with the changes cloudinabox does?

**Comment by dumblob** [comment]
Any insight regarding the domain "sharing" would be much appreciated. Any thoughts?

**Comment by downtownallday** [comment]
I'm not clear on exactly what you're asking. MiaB-LDAP has all the same DNS requirements as MiaB, whereas CiaB requires a single A record (it does not run its own nameserver).

**Comment by dumblob** [comment]
Sorry for the confusion. I wasn't sure CiaB doesn't mangle DNS records. If there is no nameserver on CiaB, then I suspect CiaB can't do any harm to DNS records set by MiaB-LDAP. Closing this as resolved then.

Thanks for your support!
