### ISSUE TITLE
Integration with MiaB-LDAP not working due to aliases

### ISSUE THREAD

**Issue by dumblob** [downtownallday/cloudinabox#6]
During integration with MiaB-LDAP, this suggestion is made:

```
IMPORTANT:

The smart host user will be sending mail FROM other users, a privilege that must be explicitly granted to x@domain.tld. This is accomplished in the Mail-in-a-Box admin interface, by adding a new
alias with these settings:

    Alias             = @suzuki.domain.tld
    Forwards to       = <leave this blank>
    Permitted-senders = mysuzuki@domain.tld

Press any key to continue
```

Unfortunately the web interface of MiaB-LDAP doesn't allow `@suzuki.domain.tld` as valid input:

![20201027_175443+0100-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/97335135-c4ffa900-187d-11eb-9e59-21050b38dad1.png)

Any ideas how to do it?

**Comment by downtownallday** [comment]
catch-all

**Comment by dumblob** [comment]
Oh, my bad. I didn't even notice what it says :cry:. Thanks!

----
Hm, but if *Catch-All* will be mentioned in the comment in the script, it'll be even smoother :wink:.
